# Site settings
permalink: /blog/:year/:month/:day/:title/
title: Nuclide
tagline: A unified developer experience for software development
fbappid: ""
gacode: "UA-44373548-2"
description: >
  Nuclide is built as a single package on top of Atom to provide hackability and the support of an active community.

  It provides a first-class development environment for React Native, Hack and Flow projects.
logo: /static/og_image.png

# baseurl determines the subpath of your site. For example if you're using an
# organisation.github.io/reponame/ basic site URL, then baseurl would be set
# as "/reponame". If you have a top-level domain URL, you can set it to "" or
# leave blank as it is now set to "" by default as discussed in:
# http://jekyllrb.com/news/2016/10/06/jekyll-3-3-is-here/

# the base hostname & protocol for your site
# If baseurl is set, then the absolute url for your site would be url/baseurl
# This was also be set to the right thing automatically for local development
# https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3
# http://jekyllrb.com/news/2016/10/06/jekyll-3-3-is-here/
url: "https://nuclide.io"

# Note: There are new filters in Jekyll 3.3 to help with absolute and relative urls
# absolute_url
# relative_url
# So you will see these used throughout the Jekyll code in this template.
# no more need for | prepend: site.url | prepend: site.baseurl
# http://jekyllrb.com/news/2016/10/06/jekyll-3-3-is-here/
# https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3

# The GitHub repo for your project
ghrepo: "facebook/nuclide"

# Build settings
# Github pages now only supports Kramdown and Rouge
# https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
# So no need to be explicit with respect to our markdown and highlighter settings since they
# cannot change.
# kramdown also automatically generates header ID's too. But we remove any auto id suffix
# in a post processing step (js/jekyll-link-anchors.js) to make the links more readable.

# For local development and testing, explicitly set kramdown settings that GitHub does
# https://help.github.com/articles/using-jekyll-with-pages/#defaults-you-can-change
kramdown:
  input: GFM
  hard_wrap: false

# Blog posts are built into to Jekyll by default, with the `_posts` directory.
# Here you can specify other types of documentation. The names here are `docs`
# and `top-level`. This means their content will be in `_docs` and `_top-level`.
# The permalink format is also given.
# http://ben.balter.com/2015/02/20/jekyll-collections/
collections:
  docs:
    output: true
    permalink: /docs/:name/
  top-level:
    output: true
    permalink: /:name/

sass:
  style: :compressed

color:
  # Provides colour for background of top header of homepage
  primary: "#2F0F56"
  # Provides colour for background of elsewhere on site
  secondary: "#e4e4e4"
  # A color that will work for buttons laid on top of primary colour
  light: "#9B4DCA"
  # Color that will work for text on top of light color
  lighttext: "#fff"
  # Color of text in the top header of homepage, must be legible on top of primary color
  headertext: "#fff"
  # Color of text on top of the secondary color background
  bodytext: "#151515"
  # Background of fixed nav header - headertext color is used for mini logo text
  nav: "#4A148C"
  # Text of links in the nav
  navtext: "#c79aff"
  # Color of link underlines in the main body, and hover background color for links
  link: "#6223b0"

# RSS Feed
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Set default open graph image for all pages
defaults:
  -
    scope:
      path: ""
    values:
      image: /static/og_image.png
